# Generated by Django 4.1.2 on 2022-11-03 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_links_links_links_github_link_and_more'),
        ('auth_app', '0002_advocateprofile_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocateprofile',
            name='links',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.links'),
        ),
    ]
