# Generated by Django 4.1.2 on 2022-11-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_advocateprofile_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocateprofile',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
