# Generated by Django 4.1.2 on 2022-10-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('short_bio', models.TextField()),
                ('long_bio', models.TextField()),
                ('advocate_years_exp', models.IntegerField()),
            ],
        ),
    ]
