# Generated by Django 4.1.2 on 2022-10-23 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_advocateprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='advocateprofile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
