# Generated by Django 4.1.2 on 2022-10-23 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_advocateprofile_id_alter_advocateprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='advocateprofile',
            name='name',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(25)]),
        ),
    ]
