# Generated by Django 4.1.2 on 2022-10-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_advocateprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocateprofile',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
