# Generated by Django 4.1.2 on 2022-11-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_advocateprofile_twitter_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocateprofile',
            old_name='long_bio',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='advocateprofile',
            name='short_bio',
        ),
    ]
