# Generated by Django 4.1.2 on 2022-11-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_rename_long_bio_advocateprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateprofile',
            name='user',
        ),
    ]
