# Generated by Django 4.1.2 on 2022-10-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_remove_advocateprofile_id_advocateprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='advocateprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
