# Generated by Django 4.1.2 on 2022-11-05 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_remove_advocateprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocateprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
