# Generated by Django 4.1.2 on 2022-10-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_remove_advocateprofile_user_advocateprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateprofile',
            name='advocate_years_exp',
        ),
        migrations.RemoveField(
            model_name='advocateprofile',
            name='long_bio',
        ),
        migrations.RemoveField(
            model_name='advocateprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='advocateprofile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='advocateprofile',
            name='short_bio',
        ),
    ]
