# Generated by Django 4.1.2 on 2022-10-23 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_remove_advocateprofile_advocate_years_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocateprofile',
            name='advocate_years_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advocateprofile',
            name='long_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advocateprofile',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='advocateprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='advocateprofile',
            name='short_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advocateprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
