# Generated by Django 4.1.2 on 2022-11-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_remove_advocateprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocateprofile',
            old_name='twitter_link',
            new_name='twitter',
        ),
    ]
