# Generated by Django 4.1.2 on 2022-10-23 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_advocateprofile_advocate_years_exp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='advocateprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
