# Generated by Django 4.1.2 on 2022-10-23 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_remove_advocateprofile_id_alter_advocateprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
