# Generated by Django 4.1.2 on 2022-10-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_alter_advocateprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocateprofile',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
