# Generated by Django 4.1.2 on 2022-10-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0012_alter_advocateprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('logo', models.ImageField(upload_to='')),
                ('summary', models.TextField()),
                ('advocates', models.ManyToManyField(to='auth_app.advocateprofile')),
            ],
        ),
    ]
