# Generated by Django 4.1.2 on 2022-10-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_advocateprofile'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='advocates',
            field=models.ManyToManyField(to='auth_app.advocateprofile'),
        ),
    ]
