# Generated by Django 4.1.2 on 2022-11-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Links',
        ),
    ]
