# Generated by Django 4.1.2 on 2022-11-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_link_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='links',
        ),
        migrations.AddField(
            model_name='links',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
