# Generated by Django 4.1.2 on 2022-11-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_links_links_links_github_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
    ]
